name: Node

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-client-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-client-${{ env.cache-name }}-
            ${{ runner.os }}-client-
            ${{ runner.os }}-
        working-directory: ./client
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./client
      - name: Lint
        run: yarn lint
        working-directory: ./client
      - name: Check git tag
        uses: bana118/action-autotag@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: package
          root: "client"
          tag_prefix: "v"
          dry_run: true
